[package]
name = "cpu"
version.workspace = true
edition.workspace = true
license-file = "../../LICENSE"

[dependencies]
format = { path = "../format" }
lz4_flex.workspace = true
rayon.workspace = true
xxhash-rust.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
