[package]
name = "cli"
version.workspace = true
edition.workspace = true
license-file = "../../LICENSE"

[[bin]]
name = "gpucomp"
path = "src/main.rs"

[dependencies]
gpu = { path = "../gpu" }
bench = { path = "../bench" }
cpu = { path = "../cpu" }
format = { path = "../format" }
clap.workspace = true
log.workspace = true
env_logger.workspace = true
anyhow.workspace = true
chrono.workspace = true

[lints]
workspace = true
